/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#3c4a42',
        'on-tertiary-container': '#523200',
        'on-secondary': '#ffffff',
        outline: '#6c7a71',
        'on-primary-fixed': '#002113',
        'surface-tint': '#006c49',
        'primary-container': '#10b981',
        'on-tertiary': '#ffffff',
        'on-surface': '#151c27',
        'inverse-surface': '#2a313d',
        'on-tertiary-fixed-variant': '#653e00',
        'inverse-primary': '#4edea3',
        'primary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#ffb95f',
        'outline-variant': '#bbcabf',
        'secondary-container': '#da3437',
        surface: '#f9f9ff',
        'on-primary-fixed-variant': '#005236',
        'secondary-fixed': '#ffdad7',
        'on-tertiary-fixed': '#2a1700',
        'primary-fixed-dim': '#4edea3',
        'surface-bright': '#f9f9ff',
        'on-error': '#ffffff',
        'surface-variant': '#dce2f3',
        secondary: '#b61722',
        'on-primary-container': '#00422b',
        error: '#ba1a1a',
        background: '#f9f9ff',
        'on-background': '#151c27',
        'surface-container-low': '#f0f3ff',
        primary: '#006c49',
        'surface-container-lowest': '#ffffff',
        'on-secondary-container': '#fffbff',
        tertiary: '#855300',
        'inverse-on-surface': '#ebf1ff',
        'surface-container': '#e7eefe',
        'secondary-fixed-dim': '#ffb3ad',
        'on-secondary-fixed': '#410004',
        'tertiary-fixed': '#ffddb8',
        'tertiary-container': '#e29100',
        'surface-dim': '#d3daea',
        'surface-container-highest': '#dce2f3',
        'on-primary': '#ffffff',
        'on-error-container': '#93000a',
        'on-secondary-fixed-variant': '#930013',
        'error-container': '#ffdad6',
        'surface-container-high': '#e2e8f8',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-md': '1rem',
        'gutter-md': '1rem',
        'stack-sm': '0.5rem',
        'stack-lg': '1.5rem',
        'margin-mobile': '1rem',
        'inset-card': '1rem',
      },
      fontFamily: {
        'headline-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-md': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
